project:
  name: EEAD-ADR
  tz: Asia/Tokyo
  adrFolder: ./docs/adr
  packages:
    - name: router
      path: ./router
      adrFolder: ./router/docs/adr
    - name: test-project
      path: ./test_project
      adrFolder: ./test_project/docs/adr
